# Teroria De los Numpy Arrays 


Los numpy Arrays por otro lado permiten la habilidad de hacer operaciones matriciales que no son nada mas que la habilidad de operar cada elemento de un array por cada elemento de otro array.

Esencial para entrenar modelos de machine larning o redes neuronales 


Los numpy Arrays son del orden de 30 veces mas rapidos que un array normal pero en consecuancia y como contrapunto para que esto sea asi son homogeneos es decir estos deben de contener tan solo un mismo tipo de dato 

# Utilizacion de Numpy en Python 

In [ ]:
# Para utilizar la libreria de Numpy tan solo tenemos que importarla por convencio se le llama np
import numpy as np

In [ ]:
#Para realizar la raiz cuadrada de un numero funcion sqrt
np.sqrt(56)

7.483314773547883

# Construyendo Numoy Arrays

## 1. Arrays


### Primera forma de construccion con np.array()

In [ ]:
# Por ejemplo una lista normal en Python 
a = [0,1,2,3,4,5,6]

type(a)

list

In [ ]:
# Con la funcion np.array() transformamos esa lista de Python en un numpy array de la siguiente forma 
print(np.array(a))

type(np.array(a))

[0 1 2 3 4 5 6]


numpy.ndarray

### 1.2 Segunda forma con la funcion np.arange()

In [ ]:
# COn esta funcion obtenemos un rango de numeros del primer al segundo parametro y el tercer parametro es el salto que da esa progresion 
# El primer parametro es inclusivo mientras que el segundo parametro es exclusivo 
b = np.arange(4, 24, 2)

print(b)

[ 4  6  8 10 12 14 16 18 20 22]


### 1.3 np.linspace()

In [ ]:
# Esta funcion recibe dos parametros esos dos parametros va a generar numeros con la misma progresion entre esos dos numeros los dos parametros son inclusivos pero tienen la misma progresion 
# o La misma linealidad peor la diferencia esque va generar la misma distancia entre los numeros que se encuentren entre estos dos parametros incluidos es decir si tenemos del 1 al 50
# Generara un array con todos los numeros del 1 al 50 ambos inckusivos pero la progresion entre estos dos sera equivalente es decir el 1, 2 asi y esto se modificara dependiendo de los dos parametros 
# que le pasemos 

c = np.linspace(1, 50)

print(c)

# Por ejemplo si le digo del 1 al 40 me generara 40 numeros con los mismos espacios del 1 al 40

d = np.linspace(1, 40)


print(d)

'''admite tambien un tercer parametro que va a ser la cantidad de numeros que nos va a generar en ese intervalo
pero con la peculiaridad de que las distancias equivalentes se van a respetar '''

e = np.linspace(1, 244, 5)

print(e)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
[ 1.          1.79591837  2.59183673  3.3877551   4.18367347  4.97959184
  5.7755102   6.57142857  7.36734694  8.16326531  8.95918367  9.75510204
 10.55102041 11.34693878 12.14285714 12.93877551 13.73469388 14.53061224
 15.32653061 16.12244898 16.91836735 17.71428571 18.51020408 19.30612245
 20.10204082 20.89795918 21.69387755 22.48979592 23.28571429 24.08163265
 24.87755102 25.67346939 26.46938776 27.26530612 28.06122449 28.85714286
 29.65306122 30.44897959 31.24489796 32.04081633 32.83673469 33.63265306
 34.42857143 35.2244898  36.02040816 36.81632653 37.6122449  38.40816327
 39.20408163 40.        ]
[  1.    61.75 122.5  183.25 244.  ]


### 1.4 np.zeros()

In [ ]:
# Va a generar un array con la longitud que nosotros le especifiquemos con todo zeros 

f = np.zeros(50)

# Nos generara un array con una longitud de 50 elementos toda llena de Zeros 

f

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 1.5 np.ones()

In [ ]:
# Va a generar un array con la longitud que nosotros le especifiquemos con todo Unos 

unesimos = np.ones(50)

# Nos va agenerar un array de 50 elementos con todod unos unos 

unesimos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 2. Dimensiones de los Numpy Arrays 

In [ ]:
# Vamos a empezar por crear un array multidimensional es decir Dos dimensiones con la funcion np.array() de 0 y 1 que son los que hemos generado antes con la funciones respectivas 
# Que son np.zeros() y np.ones()

# Por tanto 

print(f"El numero de elementos del array de 0 es :  {len(f)}")
print(f"El numero de elementos del array de 1 es :  {len(unesimos)}")



array2d = np.array([f, unesimos])

print(array2d)

'''Por tanto nos damos cuenta de que nos ha generado dos arrays dentro de un array por tanto tenemos un array 
dentro de este tenemos el primer array de 0 con los 50 elementos y posteriormente como segundo elemento del array 
original es otro array con un 50 elementos que contiene 1'''

El numero de elementos del array de 0 es :  50
El numero de elementos del array de 1 es :  50
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


'Por tanto nos damos cuenta de que nos ha generado dos arrays dentro de un array por tanto tenemos un array \ndentro de este tenemos el primer array de 0 con '

### Tenemos varias formas de ver las propiedades la primera es con la funcino de tenemos un array como vatriable y le aplicamos el .shape

In [ ]:
# Por tanto con la nomenclatura del punto podemos ver los metadatos ddel array y las funciones 

print(array2d.shape)

'''Por tanto esto nos va a decir que es un array de dos dimensiones es decir contiene dos arrays a la vez con 50 elementos 
por cada subelemento de nuestro array al que aplicamos la propiedad shape '''

(2, 50)


'Por tanto esto nos va a decir que es un array de dos dimensiones es decir contiene dos arrays a la vez con 50 elementos \npor cada subelemento de nuestro array al que aplicamos la propiedad shape '

## 2.2 arrayVariableNuestra.size

In [ ]:
# Nos dice la cantidad de elementos que se encuentra en el array al que le aplicamos el metodo size el numero total de elementos 
# En nuestro ejemplo tenemos dos arrays como elementos y cada array tiene 50 elementos por tanto 50 + 50 = 100 elementos totales 

print(array2d.size)

100


## 2.3 array.ndim

In [ ]:
# Nos dice la cantidad de dimensiones que tiene un array es decir la cantidad de sublementos que posee ese array en nuestro ejemplo es 2

print(array2d.ndim)

2


# Operaciones con Arrays 

In [ ]:
# Para hacer operaciones matriciales que es el potencial de esta libreria consiste en operar los distintos elementos de la primera matriz con la segunda matriz o asi con multiples matrices 

# Por lo tanto hacemos dos listas en Python para luego posteriormente convertirlas en Numpy Arrays con la funcion np.arrays()

lista_uno = [1, 2, 3]

lista_dos = [4, 5, 6]



In [ ]:
# ahora procedemos a crear los numpys arrays con la funcion np.array() y guardarlas en dos variables independientes

array_np_uno = np.array(lista_uno)
array_np_dos = np.array(lista_dos)



In [ ]:
# Bien debido a que Python no sporta operaciones con listas por eso llego numpy Arrays que nos permite hacer estas cosas 
'''Bien tambien nos damos cuenta que al operar esas dos listas 
las opera en forma de columna es decir el primer elemento de cada lista con el segundo elemento de cada lista 
y asi sucesivamente de forma que si multiplicamos la primera y la segunda lista 
por tanto nso devolvera un array unidemensional con el resultado que sera [4, 10, 18]'''

'''Haora bien si nosotrso queremos operar esto sin la libreria con puro python 
es mas complejo dado que sintatacticamente es bonito pero es demasiado farragoso 
recordemos que esto es una operacion sencilla y nos quedaria de la siguiente manera
aparte de tener que utilizar una funcion extra y por supuesto un for loop

[num1*num2 for num1, num2 in zip(lista_uno, lista_dos) ]'''

resultado_operaciones = array_np_uno * array_np_dos

print(f"El resultado de la operacion de [(1*4), (2*5), (3*6)] :  {resultado_operaciones}")

resultado_operacion_puro_paja_python = [num1*num2 for num1, num2 in zip(lista_uno, lista_dos)]

print(f"SIn la libreria de los numpy arrays seria de forma con el python original : {resultado_operacion_puro_paja_python}")

El resultado de la operacion de [(1*4), (2*5), (3*6)] :  [ 4 10 18]
SIn la libreria de los numpy arrays seria de forma con el python original : [4, 10, 18]


# 3. Funciones interesantes de los numpy Arrays 

## 3.1 np.reshape()

In [ ]:
# Esta funcino nos permite redfinir la forma que tiene nuestro array cuando nos referimos a redefinir nos referimos a la forma que va a tener 
# Por ejemplo en nuestro caso con el array Bidimensional tiene una forma dos porque es un array que dentro contiene 2 subelementos es decir dos arrays dentro
# Por tanto esta funcion va a tener dos parametros el primero es el array que queremos redefinir y el segundo va a ser una tupla que va a contener dos elementos 
# El pirmero de los dos elemntos va a ser la forma por ejemplo a un array de 1 dimension y el segundo elemento va a ser el numero de elementos que va a contener que va a ser la suma de los dos subarrays

unidimensionalidad_redefinida = np.reshape(array2d, (1, array2d.size))

print(f"Por tanto el nuevo array redefinido quedara asi : {unidimensionalidad_redefinida}")
print(f"la longitud de ese array es : {unidimensionalidad_redefinida.size}")

# Podemos tambien hacer que ese mismo array tenga 5 dimensiones es decir 5 subarrays dentro de el con la misma funcion e indicarle el numero de elementos por subarray que queramos 

pentadimensionalidad_redefinida = np.reshape(array2d, (5, 20))

# Otro punto importante es que cuando lo redefinimos y le decimos la cantidad de elementos que tienen que tener nuestros subarrays este tiene que ser divisible por la cantidad total de elementos 
# que se encontraba en el array original 
# Como en el primer ejemplo array original numero de elementos 100 y la cantidad de elementos del nuevo array redimensionado 100 por tanto 100 / 100 = 1 es divisible por tanto correcto ademas nos indica el numero de dimensiones que tiene
# En el segundo ejemplo array original numero de elementos 100 y la cantidad de elementos del nuevo array redimensionado 20 por tanto 100 / 20 = 5 es divisible por tanto correcto ademas nos indica el numero de dimensiones que tiene

print(f"El nuevo array Pentadimensional quedaria asi : {pentadimensionalidad_redefinida}")

Por tanto el nuevo array redefinido quedara asi : [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]]
la longitud de ese array es : 100
El nuevo array Pentadimensional quedaria asi : [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 3.2 ArrayVariable.T de transpose

In [ ]:
# Lo que hace es transformar las dimensiones verticales por las horizontales y viceversa 
# Con un array unidimensional esto no tebdra efecto dado que es una sola dimension por tanto no podemos hacer el Transpose correctamente 
# Pero cambia los valores de estas dimensiones expongamos el siguiente ejemplo
# Imaginemos que tenemos una matriz bidimensional con 5 elementos es decir con una forma de shape (2 dimensiones, 5 elementos)
# Por tanto imaginemos que el eje vertical es el de las dos dimensiones y el eje horizontal el numero de elementos por cada dimension que es 5 
# Pues con la funcion Transpose nos va generar una matriz de 5 dimensiones en el eje vertical con 2 elementos en el eje horizontal 

bidimensionalidad = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])

print(f"La matriz original queda asi : {bidimensionalidad}")

print(f"La forma de la matriz original es : {bidimensionalidad.shape}")

print(f"La matriz redimensionada con 5 dimensiones o subarray en el eje vertical y 2 elementos por dimension en el eje horizontal queda de la siguinte : {bidimensionalidad.T}")

print(f"La nueva forma de la matriz es : {bidimensionalidad.T.shape}")

La matriz original queda asi : [[ 1  2  3  4  5]
 [10 20 30 40 50]]
La forma de la matriz original es : (2, 5)
La matriz redimensionada con 5 dimensiones o subarray en el eje vertical y 2 elementos por dimension en el eje horizontal queda de la siguinte : [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
La nueva forma de la matriz es : (5, 2)


## 3.3 np.random

### 3.3.1 np.random.randint

In [ ]:
# Esta funcion se llama directamente de la libreria con la funcion.random.randint genera un numero aleatorio entre dos intervalos que nosotros que le digamos y lo genera cada vez que ejecutamos la funcion 

array_aletorios = []

#pruba = np.array([4,5,6])

for i in range(300):
  array_aletorios.append(np.random.randint(0,300))

numpy_array_aleatorios = np.array(array_aletorios)

#print(f"La matriz original  es : {array_aletorios}")

print(f"La forma original de la matriz es : {numpy_array_aleatorios.shape}")

#print(f"Pruba : {pruba.shape}")

reddfinido = np.reshape(numpy_array_aleatorios, (30, 10))

print(f"Le hacmeos un Transpose para que quede en el eje vetical 5 dimensione y el eje horizontal 2 elementos por dimension que son : {reddfinido.T}")

print(f"Le hacmeos un Transpose para que quede en el eje vetical 5 dimensione y el eje horizontal 2 elementos por dimension que son : {reddfinido.T.shape}")

La forma original de la matriz es : (300,)
Le hacmeos un Transpose para que quede en el eje vetical 5 dimensione y el eje horizontal 2 elementos por dimension que son : [[ 31 200  86 131  16 193 274 102 111 170  63 207 226 153 277 106  45 294
   78 116   3  68 155 210 102 126 144 297 165 112]
 [241 162 135 264 246 285 183 115 257 250 151 281 175 160 200  48  75 180
  168 295 154 230  64  31 213  88  17  39   1  66]
 [ 78 175 274 215 143 115 129 213  38 199 193 151 118 100 138  79 287  43
   51  28 285 261  14 236  65 221 167 223  70 124]
 [ 51   6 196 166 172  78  67 199 245  50 270 198 134 266 282  79 135 206
   84 200 254 203 279 286 210 231   8 102 280 269]
 [ 58 124 217  50  78  85 165 124 252 131   1 108 199  91 273 297 132 259
  176 136 118  77 128 279 248  21  67 119 138 114]
 [168 214 166 184 225 150  84 137 165 264 253 205 251 281 202 275  16  26
  204 206 153  81 109 184 146 279 268 224  22 247]
 [246 222  43 229  84 107  29 165 256  87 248 128 293   2 124 292 278 231
   55  

## 3.4 np.where

In [ ]:
# Como su propio nombre indica el where es para establecer una condicion y el metodo es propio de numpy y tiene 3 parametros 
# Estos tres parametros son el primero es nuestro array objetivo al que le establecemos una condicion, el segundo parametro es si esa condicion es verdadera que hacemos 
# y el tercer parametro es si esa condicion es falsa que tenemos que hacer

# Por tanto en nuestro array bidimensional de 0 y 1s le decimos que cuando encuentre 1 nos lo multiple por 10 y cuando no que le reste 5

'''Por tanto ha ido recorriendo la coleccion cuando se encontraba cero o 0 al no cumplir 
la condicion le resto 5 quedando - 5 y cuando se encontro 1 lo multiplico por 10 porque se cumplia la condicion
de que el elemento fuera igual a 1, tambien puede ser que los dejes igual cuando no cumple la condicion o que no haga nada '''

np.where(array2d == 1, array2d * 10, array2d - 5)

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# 4. Estadistica 

## 4.1 Distribuciones 

### 4.1.1 Distribucion Normal 

In [ ]:
# vamos ha hacer una distribucion normal que es la tipica de un grupo de 1000 personas por ejemplo la mayoria de la gente se encontrara entre la media y a medida que vayamos 
# a los extremos la distribucion de las personas se alejara 

# Por lo que la funcion nomral de random nos va a generar un array o conjunto de datos que tendra una serie de parametros en concreto tres 
# El primer parametro representa la media de los valores de esa distribucion
# El segundo parametro representa la desviacion que puede tomar cada valor de la distribucion es decir cuanto se puede alejar cada valor de la distribucion 
# El tercero representa la cantidad de datos totales que hay en la distribucion 

arrray_distribucion_normal = np.random.normal(1.75, 0.05, 1000)

print(f"Nuestro array de dsitribucion normal es : {arrray_distribucion_normal}")

Nuestro array de dsitribucion normal es : [1.7817168  1.81826054 1.78791197 1.71381972 1.76379301 1.77421819
 1.71260612 1.70680577 1.69471299 1.73156965 1.7560092  1.67135525
 1.77215346 1.70425714 1.68468784 1.70638426 1.75344953 1.69846986
 1.76221519 1.74260762 1.71937504 1.65141001 1.7841402  1.74992003
 1.86335994 1.6346813  1.76473897 1.77624416 1.69539019 1.78719459
 1.75174285 1.68902494 1.73461473 1.67629734 1.63782837 1.77521585
 1.72428962 1.71699568 1.68201802 1.80495994 1.75732151 1.77410969
 1.72449716 1.70919239 1.77923887 1.78038538 1.8053292  1.8222832
 1.81518876 1.74355686 1.84238776 1.7824656  1.73461728 1.71756863
 1.73434667 1.81444552 1.78169211 1.74712212 1.72787492 1.7194139
 1.76709895 1.71357043 1.73664461 1.75499289 1.69022829 1.70270757
 1.72768404 1.7398403  1.73921391 1.69880492 1.73404089 1.73078045
 1.75872968 1.68559834 1.7951982  1.72672307 1.82006359 1.74422464
 1.78619002 1.70713926 1.73278843 1.67828598 1.80857455 1.79317771
 1.78362591 1.76241115

### 4.1.2 np.mean()

In [ ]:
# Esta funcion nos calcula rapidamente cual es la media de altura de todo el conjunto de elementos de nuestro array que representa nuestra distribucion 

np.mean(arrray_distribucion_normal)

1.7498689541832588

### 4.1.3 np.median()

In [ ]:
# Sera el elemento que justo este a la mitad del total de datos de nuestra distribucion es decir si tenemos 1000 el elemento que esta en la media es 1000 / 2 = 500 sera ese pero esta 
# Funcion ademas ordena internamente los elementos previamente 

np.median(arrray_distribucion_normal)

1.7508010490909605

### 4.1.4 np.(std)

In [ ]:
# Esta propiedad o funcion nos devulve la desviacion es decir cuanto puede variar un elemento de nuestro conjunto de la distribucion cuanto de lejos puede darse respecto a le media u otros parametros

np.std(arrray_distribucion_normal)

0.05052531897391376